
project_id = "rxpgqunqsegypssoqpyf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions.kiwify-webhook]
verify_jwt = false

[functions.max-webhook]
verify_jwt = false

[functions.create-client-users]
verify_jwt = false

[functions.creative-generator]
verify_jwt = false

[functions.dall-e-generator]
verify_jwt = false

[functions.pdf-analyzer]
verify_jwt = false

[functions.openai-usage-monitor]
verify_jwt = false

[functions.reformat-existing-plans]
verify_jwt = false

[functions.analyze-business-idea]
verify_jwt = false

[functions.admin-api-config]
verify_jwt = true

[functions.get-central-api-config]
verify_jwt = true

[functions.bulk-create-parceria-users]
verify_jwt = false

[functions.process-kiwify-retroactive]
verify_jwt = false

[functions.create-parceria-user]
verify_jwt = false

[functions.generate-gamified-funnel]
verify_jwt = false

[functions.dall-e-generator]
verify_jwt = false

[functions.generate-personalized-message]
verify_jwt = false

[functions.bulk-generate-parceria-plans]
verify_jwt = false

[functions.meta-ads-api]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.openai-usage-monitor]
verify_jwt = false

[functions.admin-api-config]
verify_jwt = true

[functions.get-central-api-config]
verify_jwt = true

[functions.kiwify-webhook]
verify_jwt = false

[functions.max-webhook]
verify_jwt = false

[functions.create-carol-gestor]
verify_jwt = false

[functions.delete-gestor]
verify_jwt = false

[functions.create-gestor]
verify_jwt = false

[functions.fix-client-auth]
verify_jwt = false

[functions.bulk-generate-plans]
verify_jwt = false

[functions.create-client-users]
verify_jwt = false

[functions.create-parceria-user]
verify_jwt = false

[functions.kiwify-webhook]
verify_jwt = false

[functions.max-webhook]
verify_jwt = false

[functions.whatsapp-waseller-auto-dispatch]
verify_jwt = false

[functions.process-kiwify-retroactive]
verify_jwt = false

[functions.get-central-api-config]
verify_jwt = true

[functions.admin-api-config]
verify_jwt = true

[functions.save-api-config]
verify_jwt = true

[functions.waseller-send-message]
verify_jwt = false
