project_id = "rxpgqunqsegypssoqpyf"

[functions.evolution-webhook]
verify_jwt = false

[functions.evolution-verify]
verify_jwt = false

[functions.evolution-recover-connection]
verify_jwt = false

[functions.evolution-send-text]
verify_jwt = false

[functions.evolution-check-connection]
verify_jwt = false

[functions.evolution-diagnose]
verify_jwt = false

[functions.evolution-send-message]
verify_jwt = false

[functions.evolution-process-recovery-queue]
verify_jwt = false

[functions.evolution-discover-endpoints]
verify_jwt = false
